version: '2.3'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"  
    volumes:
      - ./app:/app/app 
      - ./logs:/app/logs
      - ./malinka_service/users.db:/app/malinka_service/users.db

    environment:
      - FLASK_APP=app 
      - FLASK_ENV=development