version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "1000:1000"  
    volumes:
      - /dev/i2c-1:/dev/i2c-1  
      - ./app:/app/app  
      - ./pn532_handler.py:/app/pn532_handler.py  
    environment:
      - FLASK_APP=app/app.py  
      - FLASK_ENV=development
    privileged: true
    command: flask run --host=0.0.0.0