version: '2.3'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"  
    volumes:
      - ./logs/app.log:/app/logs/app.log
      - ./users.db:/app/users.db

    environment:
      - FLASK_APP=app 
      - FLASK_ENV=development