version: '2.3'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"  
    volumes:
       - ./logs:/app/logs
       - ./data:/app/data

    environment:
      - FLASK_APP=app 
      - FLASK_ENV=development