FROM arm32v7/python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install -r requirements.txt

COPY . .

EXPOSE 8080

CMD python app.py