version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"  
    volumes:
      - ./app:/app/app 
    environment:
      - FLASK_APP=app 
      - FLASK_ENV=development