ARG PYTHON_VERSION=3.9.6
FROM python:${PYTHON_VERSION}-slim as base

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ python3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install greenlet --no-binary :all:
RUN python3 -m pip install wheel --no-binary :all:
RUN python3 -m pip install -r requirements.txt
COPY . .

EXPOSE 8080

CMD python app.py